/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuditIndexRouteImport } from './routes/api/audit/index'
import { Route as ApiAuthUsersRouteImport } from './routes/api/auth/users'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthUsersIdRouteImport } from './routes/api/auth/users.$id'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditIndexRoute = ApiAuditIndexRouteImport.update({
  id: '/api/audit/',
  path: '/api/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUsersRoute = ApiAuthUsersRouteImport.update({
  id: '/api/auth/users',
  path: '/api/auth/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthUsersIdRoute = ApiAuthUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAuthUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/users': typeof ApiAuthUsersRouteWithChildren
  '/api/audit/': typeof ApiAuditIndexRoute
  '/api/auth/users/$id': typeof ApiAuthUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/users': typeof ApiAuthUsersRouteWithChildren
  '/api/audit': typeof ApiAuditIndexRoute
  '/api/auth/users/$id': typeof ApiAuthUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/users': typeof ApiAuthUsersRouteWithChildren
  '/api/audit/': typeof ApiAuditIndexRoute
  '/api/auth/users/$id': typeof ApiAuthUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/users'
    | '/api/audit/'
    | '/api/auth/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/users'
    | '/api/audit'
    | '/api/auth/users/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/users'
    | '/api/audit/'
    | '/api/auth/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthUsersRoute: typeof ApiAuthUsersRouteWithChildren
  ApiAuditIndexRoute: typeof ApiAuditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit/': {
      id: '/api/audit/'
      path: '/api/audit'
      fullPath: '/api/audit/'
      preLoaderRoute: typeof ApiAuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/users': {
      id: '/api/auth/users'
      path: '/api/auth/users'
      fullPath: '/api/auth/users'
      preLoaderRoute: typeof ApiAuthUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/users/$id': {
      id: '/api/auth/users/$id'
      path: '/$id'
      fullPath: '/api/auth/users/$id'
      preLoaderRoute: typeof ApiAuthUsersIdRouteImport
      parentRoute: typeof ApiAuthUsersRoute
    }
  }
}

interface ApiAuthUsersRouteChildren {
  ApiAuthUsersIdRoute: typeof ApiAuthUsersIdRoute
}

const ApiAuthUsersRouteChildren: ApiAuthUsersRouteChildren = {
  ApiAuthUsersIdRoute: ApiAuthUsersIdRoute,
}

const ApiAuthUsersRouteWithChildren = ApiAuthUsersRoute._addFileChildren(
  ApiAuthUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthUsersRoute: ApiAuthUsersRouteWithChildren,
  ApiAuditIndexRoute: ApiAuditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
